#!/bin/bash
# vim: tw=0
# from https://github.com/gabebw/dotfiles/blob/main/install.sh

set -eo

color() {
  local colornumber="$1"
  shift
  tput setaf "$colornumber"
  echo "$*"
  tput sgr0
}

red() { color 1 "$*"; }
green() { color 2 "$*"; }
yellow() { color 3 "$*"; }

info() {
  green "=== $*"
}

error() {
  red "!! $*"
}

install_dir="$(cd "$(dirname "$0")" && pwd)"

stay_awake_while() {
  caffeinate -dims "$@"
}

install_taps() {
  local brewfile=$1
  grep "^tap " "$brewfile" | while read -r line; do
    tap_name=$(echo "$line" | sed "s/tap '\\(.*\\)'/\\1/")
    brew tap "$tap_name" 2>/dev/null || yellow "Warning: failed to tap $tap_name"
  done
}

quietly_brew_bundle() {
  local brewfile=$1
  shift
  local regex='(^Using )|Homebrew Bundle complete|Skipping install of|It is not currently installed|Verifying SHA-256|==> (Downloading|Purging)|Already downloaded:|No SHA-256'
  stay_awake_while brew bundle --file="$brewfile" "$@" | (grep -vE "$regex" || true)
}

command_does_not_exist() {
  ! command -v "$1" >/dev/null
}

info "Checking for command-line tools..."
if command_does_not_exist xcodebuild; then
  stay_awake_while xcode-select --install
fi

info "Installing Homebrew (if not already installed)..."
if command_does_not_exist brew; then
  stay_awake_while /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
  (
    echo
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"'
  ) >>"$HOME/.zprofile"
fi

info "Installing Homebrew packages..."
brew install mas 2>/dev/null

info "Tapping Homebrew repositories..."
install_taps "$install_dir/Brewfile"

info "Installing formulae..."
quietly_brew_bundle "$install_dir/Brewfile" --verbose || true
quietly_brew_bundle "$install_dir/Brewfile.casks" --verbose || true
quietly_brew_bundle "$install_dir/Brewfile.mas" --verbose || true

if ! echo "$SHELL" | grep -Fq zsh; then
  info "Your shell is not Zsh. Changing it to Zsh..."
  chsh -s /bin/zsh
fi

info "Linking dotfiles into ~..."
# Before `rcup` runs, there is no ~/.rcrc, so we must tell `rcup` where to look.
# We need the rcrc because it tells `rcup` to ignore thousands of useless Vim
# backup files that slow it down significantly.
export RCRC=rcrc
stay_awake_while rcup -d .

info "Installing ASDF language version manager..."
alias install_asdf_plugin=add_or_update_asdf_plugin
add_or_update_asdf_plugin() {
  local name="$1"
  local url="$2"

  if ! asdf plugin list | grep -Fq "$name"; then
    asdf plugin add "$name" "$url"
  else
    asdf plugin update "$name"
  fi
}

declare -a languages=(
  "bun",
  "nodejs"
  "python"
  "ruby"
  "rust"
  "golang"
)

for language in "${languages[@]}"; do
  add_or_update_asdf_plugin "$language"
done

info "Success!"
yellow "== Post-install instructions =="
yellow "1. Remap Caps Lock to CTRL in the Keyboard prefpane"
yellow "2. Make sure to install TMUX plugins: prefix+I"
