#!/bin/bash

function cd () {
	if   [[ "x$*" == "x..." ]]; then
		cd ../..
			elif [[ "x$*" == "x...." ]]; then
			cd ../../..
			elif [[ "x$*" == "x....." ]]; then
			cd ../../../..
			elif [[ "x$*" == "x......" ]]; then
			cd ../../../../..
	else
		z "$@"
			fi
}
