#!/bin/bash

function gb(){
  if [[ -z "$1" ]]; then
    echo "No branch name :(" >&2
    return 1
  fi
  local branch="$1"
  local base=$2
  if [[ -n "$base" ]]; then
    git checkout -b "$branch" "$base"
  else
    git checkout -b "$branch"
  fi
}
