#!/bin/bash

gcm(){
  local commit_message=$@
  local branch=$(git current-branch )
  if [[ "$#" == 0 ]]; then
    git master-to-main-wrapper checkout %BRANCH%
  else
    # Grab JIRA ticket name (if any) and prefix it to the commit.
    if [[ "$branch" =~ '^([A-Z]{2,}-[0-9]+)' ]]; then
      # The magic "$match" array variable now contains the groups we matched
      # (1-indexed).
      ticket_number=$match[1]
      commit_message="$ticket_number $commit_message"
    fi
    local commit_message_length=$(echo -n "$commit_message" | wc -c | xargs echo -n)
    if [[ "$commit_message_length" -gt 50 ]]; then
      echo "Commit message length ($commit_message_length) > 50, not committing" >&2
      return 1
    else
      git commit -m "$commit_message"
    fi
  fi
}
