#!/bin/bash

new-project(){
  if [[ $# == 0 ]]; then
    printf "Project name? "
    read project_name
  else
    project_name=$1
  fi
  local project_name=${project_name// /-}
  pushd personal >/dev/null
  if [[ -d "$project_name" ]]; then
    echo "!! Project directory with that name already exists" >&2
    return 1
  fi
  if [[ -f "$project_name" ]]; then
    echo "!! Project FILE with that name already exists" >&2
    return 1
  fi
  mkdir "$project_name" && tcd "./$project_name"
  popd >/dev/null
}
