import = ["~/.config/alacritty/catppuccin_mocha.toml"]

[shell]
program = "/bin/zsh"

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "alacritty"

[font]
size = 18

[font.bold]
family = "SauceCodePro Nerd Font Mono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 1

[font.italic]
family = "SauceCodePro Nerd Font Mono"
style = "Semibold Italic"

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 4

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[scrolling]
history = 65536
multiplier = 3

[window]
decorations = "full"
dynamic_padding = false
option_as_alt = "Both"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 10
y = 5
