# Configuration for Alacritty, the GPU enhanced terminal emulator.

window:
  dimensions:
    columns: 0
    lines: 0
  padding:
    x: 10
    y: 5
  dynamic_padding: false
  decorations: full
scrolling:
  history: 65536
  multiplier: 3
mouse:
  url:
    launcher: open
    modifiers: Control
font:
  normal: 
    family: Source Code Pro
    style: Regular
  bold:
    family: Source Code Pro
    style: Bold
  italic: 
    family: Source Code Pro
    style: Semibold Italic
  size: 17
  offset:
    y: 4
    x: 0
  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: false

draw_bold_text_with_bright_colors: true

# Colors (One Dark)
colors:
  # Default colors
  primary:
    background: '#0c0c0c'
    foreground: '#e0e0e0'

  cursor:
    text: '#000000'
    cursor: '#fea726'

  selection:
    text: '#fefefe'
    background: '#444344'

  # Normal colors
  normal:
    # NOTE: Use '#131613' for the `black` color if you'd like to see
    # black text on the background.
    black:   '#212121'
    red:     '#f82a71'
    green:   '#a6e12d'
    yellow:  '#ffa727'
    blue:    '#ae80fe'
    magenta: '#f82a71'
    cyan:    '#66d8ee'
    white:   '#cfcfc1'

  # Bright colors
  bright:
    black:   '#74705d'
    red:     '#f82a71'
    green:   '#a6e12d'
    yellow:  '#e6db73'
    blue:    '#ae80fe'
    magenta: '#f82a71'
    cyan:    '#66d8ee'
    white:   '#f7f7f1'
key_bindings:
  - { key: F,        mods: Command, action: ToggleFullscreen }

