# Configuration for Alacritty, the GPU enhanced terminal emulator.

window:
  dimensions:
    columns: 0
    lines: 0
  padding:
    x: 10
    y: 5
  dynamic_padding: false
  decorations: full
scrolling:
  history: 65536
  multiplier: 3
mouse:
  url:
    launcher: open
    modifiers: Control
font:
  normal:
    family: SauceCodePro Nerd Font Mono
    style: Regular
  bold:
    family: SauceCodePro Nerd Font Mono
    style: Bold
  italic:
    family: SauceCodePro Nerd Font Mono
    style: Semibold Italic
  size: 17
  offset:
    y: 4
    x: 0
  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: false

draw_bold_text_with_bright_colors: true

# Colors (One Dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '#1d2021'
    background: "#282828"
    # soft contrast: background = '#32302f'
    foreground: "#ebdbb2"

  cursor:
    text: "#000000"
    cursor: "#fea726"

  selection:
    text: "#fefefe"
    background: "#444344"

  # Normal colors
  # Normal colors
  normal:
    black: "#282828"
    red: "#cc241d"
    green: "#98971a"
    yellow: "#d79921"
    blue: "#458588"
    magenta: "#b16286"
    cyan: "#689d6a"
    white: "#a89984"

  # Bright colors
  bright:
    black: "#928374"
    red: "#fb4934"
    green: "#b8bb26"
    yellow: "#fabd2f"
    blue: "#83a598"
    magenta: "#d3869b"
    cyan: "#8ec07c"
    white: "#ebdbb2"
key_bindings:
  - { key: F, mods: Command, action: ToggleFullscreen }
