#!/bin/bash

# youtube-dl
alias yt='youtube-dl --output "$PWD/%(extractor_key)s/%(uploader)s [%(channel_id)s]/%(title)s [%(id)s].%(ext)s"'
alias ytp='youtube-dl --output "$PWD/%(extractor_key)s/%(uploader)s [%(channel_id)s]/%(playlist)s/%(playlist_index)s - %(title)s [%(id)s].%(ext)s"'
alias audio='youtube-dl --ignore-config -f bestaudio --extract-audio --audio-format mp3 --embed-thumbnail --add-metadata --audio-quality 0 --output "$PWD/%(uploader)s - %(title)s.%(ext)s"'

function ytinfo() {
	youtube-dl --ignore-config --dump-json "$1" | jq
}

# alias act='op run --env-file="$HOME/.config/op/gh.env" -- act -s GITHUB_TOKEN'
# alias aws='op run --env-file="$HOME/.config/op/aws.env" -- aws'
# alias gh='op run --env-file=$HOME/.config/op/gh.env -- gh'

alias re-source="source ~/.localrc"

export VISUAL="nvim"

alias vi='$VISUAL'
alias vim='$VISUAL'

alias cd="z"

alias reload!='RELOAD=1 source ~/.zshrc'
alias qq="cd . && source ~/.zshrc"
alias ls="exa"
alias ll="exa -alh"
alias tree="exa --tree"
alias diff="colordiff -u"
alias pn="pnpm"
alias dig="dig +noall +answer +multiline"

alias gs='git status -sb'

alias mkdir="mkdir -p"
alias cat="bat"
alias rm="trash"
alias tmux="tmux -2"
alias ssh='TERM=xterm-256color ssh'
# alias grep="egrep --color=auto"

alias sed="sed -E"                 # Use modern regexps for sed, i.e. "(one|two)", not "\(one\|two\)"
alias crontab="VISUAL=vim crontab" # Remove vim flags for crontab -e

alias k='kubectl --kubeconfig $HOME/.kubeconfig-integrations-developer'
