export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_AUTO_UPDATE_SECS=604800
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_INSTALL_CLEANUP=1
export HOMEBREW_NO_ENV_HINTS=1
export FZF_DEFAULT_COMMAND='rg --hidden --files --ignore-file ~/.ignore'
export FZF_CTRL_T_COMMAND=$FZF_DEFAULT_COMMAND
export TIMEFMT=$'\nreal\t%*E\nuser\t%*U\nsys\t%*S'

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

export JAVA_HOME=$(/usr/libexec/java_home -v1.11)

export ANDROID_SDK_ROOT=${BREW_HOME}/share/android-commandlinetools
export ANDROID_HOME=${BREW_HOME}/share/android-commandlinetools
if [[ -d "${ANDROID_HOME}/emulator" ]]; then
  export PATH=$PATH:${ANDROID_HOME}/emulator
fi

eval "$(/opt/homebrew/bin/brew shellenv)"

# pnpm
export PNPM_HOME="/Users/drewdelianides/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# bun completions
[ -s "/Users/drewdelianides/.bun/_bun" ] && source "/Users/drewdelianides/.bun/_bun"
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

export GOPATH="$HOME/Github/Golang/src/go"
export GOBIN="$HOME/Github/Golang/src/go/bin"

[ -s "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"

export PATH="/Users/adelianides/.local/bin:$PATH"
