stty -ixon

export ZPLUG_HOME=/opt/homebrew/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug "mafredri/zsh-async"
zplug 'zsh-users/zsh-syntax-highlighting', defer:2
zplug 'zsh-users/zsh-completions', defer:2
zplug 'zsh-users/zsh-autosuggestions', defer:2
zplug "zsh-users/zsh-history-substring-search", defer:2
zplug "jeffreytse/zsh-vi-mode"
zplug "plugins/git", from:oh-my-zsh
zplug "lib/clipboard", from:oh-my-zsh, if:"[[ $OSTYPE == *darwin* ]]"
zplug "Aloxaf/fzf-tab", defer:3

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'
ZVM_VI_ESCAPE_BINDKEY=jj
ZVM_VI_INSERT_ESCAPE_BINDKEY=jj
ZVM_INIT_MODE=sourcing

zstyle ':fzf-tab:complete:cd:*' fzf-preview 'exa -1 --color=always $realpath'

zplug load

. $(brew --prefix asdf)/libexec/asdf.sh

eval "$(direnv hook zsh)";
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"

# shellcheck disable=SC1090
[ -f ~/.aliases ] && source ~/.aliases;
# shellcheck disable=SC1090
[ -f ~/.localrc ] && source ~/.localrc;
# shellcheck disable=SC1090
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh;

for zsh_source in $HOME/.zsh/config/*.zsh; do
	source $zsh_source
done

enable-fzf-tab

# Returns the name of the most recent tmux session, sorted by time the session
# was last attached.
if ! inside_ssh && ! in_vs_code; then
  connect_to_most_recent_tmux_session
fi
