export PATH="$PATH:~/.bin"

ZSH_LOCAL="$HOME/.zsh.local"
[ ! -d $ZSH_LOCAL ] && mkdir -p "$(dirname $ZSH_LOCAL)"
source "${ZSH_LOCAL}"

ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "${ZINIT_HOME}/zinit.zsh"

zinit pack for ls_colors

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)

# fix underline in VSCode Terminal
local znt_history_active_text=reverse

zinit lucid for \
    atinit"
      ZSH_TMUX_FIXTERM=false
      ZSH_TMUX_AUTOSTART=false
      ZSH_TMUX_AUTOQUIT=false
      ZSH_TMUX_DEFAULT_SESSION_NAME=main
      ZSH_TMUX_AUTOCONNECT=false" \
    OMZP::tmux \
    atinit"HIST_STAMPS=dd.mm.yyyy" \
    OMZL::history.zsh

zinit wait lucid for \
  atload"
      alias ..='cd ..'
      alias ...='cd ../..'
      alias ....='cd ../../..'
      alias .....='cd ../../../..'"\
    OMZL::directories.zsh \
    OMZL::git.zsh \
    OMZL::grep.zsh \
    OMZL::key-bindings.zsh \
    OMZP::cp \
    OMZP::colored-man-pages \
    OMZP::command-not-found \
    OMZP::copyfile \
    OMZP::copypath \
    OMZP::dirhistory \
    OMZP::extract \
    OMZP::colorize \
    OMZP::git \
    OMZP::fzf \
    OMZP::zsh-interactive-cd \
    Aloxaf/fzf-tab \
    psprint/zsh-navigation-tools \
  atinit"ZVM_INIT_MODE=sourcing;ZVM_VI_ESCAPE_BINDKEY=jj;ZVM_VI_INSERT_ESCAPE_BINDKEY=jj" \
    jeffreytse/zsh-vi-mode

zinit wait lucid for \
    light-mode atinit"ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20" atload"_zsh_autosuggest_start" \
  zsh-users/zsh-autosuggestions \
    light-mode atinit"
      typeset -gA FAST_HIGHLIGHT; FAST_HIGHLIGHT[git-cmsg-len]=100;
      zpcompinit; zpcdreplay" \
  zdharma-continuum/fast-syntax-highlighting \
    atpull'zinit creinstall -q .' \
    atinit"
      zstyle ':completion:*' completer _expand _complete _ignored _approximate
      zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
      zstyle ':completion:*' menu select=2
      zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'
      zstyle ':completion:*:*:*:*:processes' command 'ps -u $USER -o pid,user,comm,cmd -w -w'
      zstyle ':completion:*:descriptions' format '-- %d --'
      zstyle ':completion:*:processes' command 'ps -au$USER'
      zstyle ':completion:complete:*:options' sort false
      zstyle ':fzf-tab:complete:_zlua:*' query-string input
      zstyle ':fzf-tab:complete:cd:*' extra-opts --preview=$extract'exa -1 --color=always ${~ctxt[hpre]}$in'
      zstyle ':fzf-tab:complete:kill:argument-rest' extra-opts --preview=$extract'ps --pid=$in[(w)1] -o cmd --no-headers -w -w' --preview-window=down:3:wrap" \
    blockf light-mode \
  zsh-users/zsh-completions \
    atinit"
      zstyle :history-search-multi-word page-size 10
      zstyle :history-search-multi-word highlight-color fg=red,bold
      zstyle :plugin:history-search-multi-word reset-prompt-protect 1" \
    bindmap"^R -> ^H" \
  zdharma-continuum/history-search-multi-word \
  zsh-users/zsh-history-substring-search \
  joshskidmore/zsh-fzf-history-search

zinit ice as"command" from"gh-r" \
    atclone"./starship init zsh > init.zsh; ./starship completions zsh > _starship" \
    atpull"%atclone" src"init.zsh"

zinit light starship/starship

zinit lucid light-mode for \
  as"command" from"gh-r" bpick'*darwin_arm*' \
  @junegunn/fzf

zinit lucid light-mode from"gh-r" as"command" bpick'*darwin*' for \
    atload'
        alias l="eza -abghHlS --git --group-directories-first"
        alias ls="eza"
        alias ll="eza -alh"
        alias tree="eza --tree"
        eval "$(zoxide init --no-aliases zsh)"
        alias z="__zoxide_z"
    ' pick'zoxide/zoxide' \
        @ajeetdsouza/zoxide \
    mv'ripgrep* -> rg' pick'rg/rg' \
        @BurntSushi/ripgrep \
    mv'fd* -> fd' pick'fd/fd' \
        @sharkdp/fd \
    mv'bat* -> bat' pick'bat/bat' atload'
        export MANPAGER="bat --plain"
        alias cat="bat"
    ' \
        @sharkdp/bat \
    mv'delta* -> delta' pick'delta/delta' \
        @dandavison/delta \

setopt APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS # IGNORE DUPLICATION COMMAND HISTORY LIST
setopt HIST_IGNORE_SPACE
setopt HIST_VERIFY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY # SHARE COMMAND HISTORY DATA
setopt NO_BG_NICE
setopt NO_HUP                    # don't kill background jobs when the shell exits
setopt NO_LIST_BEEP
setopt LOCAL_OPTIONS
setopt LOCAL_TRAPS
setopt PROMPT_SUBST
setopt EXTENDED_GLOB
setopt INC_APPEND_HISTORY
setopt AUTOPUSHD
unsetopt AUTO_CD

export VISUAL="nvim"
export MANPAGER="bat --plain"


source $HOME/.localrc
source $HOME/.aliases

function sesh-sessions() {
  {
    exec </dev/tty
    exec <&1
    local session
    session=$(sesh list | fzf --height 40% --reverse --border-label ' sesh ' --border --prompt '⚡  ')
    zle reset-prompt > /dev/null 2>&1 || true
    [[ -z "$session" ]] && return
    sesh connect $session
  }
}

zle     -N            sesh-sessions
bindkey -M emacs '^O' sesh-sessions
bindkey -M vicmd '^O' sesh-sessions
bindkey -M viins '^O' sesh-sessions

zicompinit

export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"


# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/drewdelianides/.lmstudio/bin"
# End of LM Studio CLI section

